# Generated by Django 4.2.6 on 2023-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_name', models.ManyToManyField(to='myapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_name',
            field=models.ManyToManyField(to='myapp.teacher'),
        ),
    ]
