# Generated by Django 4.2.6 on 2023-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_name',
            field=models.ManyToManyField(blank=True, to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_name',
            field=models.ManyToManyField(blank=True, to='myapp.student'),
        ),
    ]
