# Generated by Django 4.2.6 on 2023-10-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_teacher_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student_name',
        ),
    ]
