# Generated by Django 4.2.6 on 2023-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_name',
            field=models.ManyToManyField(blank=True, related_name='teacher_name', to='myapp.teacher'),
        ),
    ]
